# Netlify Configuration File for Zola Static Site

[build]
  # The command to run to build your project
  command = "zola build"
  
  # The directory to publish after the build
  publish = "public"

# Environment Variables
[build.environment]
  ZOLA_VERSION = "0.20.0"  # Ensure the correct version of Zola
  PATH = "/opt/buildhome/.cargo/bin:$PATH"  # Add Cargo binaries to the path if needed

# Pre-build steps (Before the install step)
[build.before_install]
  # Install required system dependencies if missing
  command = "apt-get update && apt-get install -y mkdir touch"

# Plugins
[[plugins]]
  package = "@netlify/plugin-zola"  # Use the official Zola plugin
