[build]
  command = "echo $PATH && which mkdir && which touch && zola --version && zola build"
  publish = "public"

[build.environment]
  ZOLA_VERSION = "0.20.0"
  PATH = "/opt/buildhome/.cargo/bin:$PATH"

[[plugins]]
  package = "@netlify/plugin-zola"
